server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;
    server_name opencti.cyberthreatintel.training;
    ssl_certificate /etc/nginx/conf.d/certs/opencti.cyberthreatintel.training/fullchain.pem;
    ssl_certificate_key /etc/nginx/conf.d/certs/opencti.cyberthreatintel.training/privkey.pem;
    location / {
        proxy_cache off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        chunked_transfer_encoding off;
        proxy_pass http://opencti:8080;
    }
}